### ISSUE TITLE
#5 - Validar a Entrada: Nova Transição

### ISSUE THREAD

**Issue by darlannakamura** [darlannakamura/maquina-de-turing#5]
Criar uma classe separada, chamada Validador: que será responsável por verificar se a entrada do usuário está seguindo o padrão: TOKEN;TOKEN;DIRECAO

TOKEN = Letra/Número/VAZIO
DIRECAO = L/R/S

Caso saia desse padrão, deve informar o erro ao usuário.

**Comment by matheuspalmeir** [comment]
Feito
